"""Urinal-cleaning building blocks for fixture-relative contact workflows."""

from tiptop.urinal.localization import (
    detect_fixture_mask_with_sam3,
    FixtureLocalizationError,
    draw_fixture_overlay,
    estimate_urinal_frame_from_mask,
    estimate_urinal_frame_from_roi,
    fixture_prompt_texts_from_cfg,
    fixture_registration_mode_from_cfg,
    fixture_roi_from_cfg,
    load_fixture_estimate,
    normalize_fixture_roi,
    save_fixture_estimate,
    select_best_fixture_mask_candidate,
)
from tiptop.urinal.primitives import build_dry_run_primitives, primitive_plan_to_dict, save_primitive_plan
from tiptop.urinal.types import (
    DryRunValidationReport,
    CleaningZone,
    FailureCode,
    FixtureLocalizationMode,
    FixtureObservation,
    InspectionDecision,
    InspectionResult,
    PrimitivePlan,
    PrimitiveValidationResult,
    RunOutcome,
    UrinalFrameEstimate,
)
from tiptop.urinal.validation import (
    PosePlanAttempt,
    build_motion_gen_pose_planner,
    dry_run_validation_report_to_dict,
    primitive_validation_result_to_dict,
    resolve_validation_start_q,
    save_dry_run_validation_report,
    validate_dry_run_primitives,
)
from tiptop.urinal.zones import ZONE_SEQUENCE, build_cleaning_zones, cleaning_zone_to_dict, save_cleaning_zones

__all__ = [
    "CleaningZone",
    "DryRunValidationReport",
    "detect_fixture_mask_with_sam3",
    "FailureCode",
    "FixtureLocalizationError",
    "FixtureLocalizationMode",
    "FixtureObservation",
    "InspectionDecision",
    "InspectionResult",
    "PosePlanAttempt",
    "PrimitivePlan",
    "PrimitiveValidationResult",
    "RunOutcome",
    "ZONE_SEQUENCE",
    "UrinalFrameEstimate",
    "build_cleaning_zones",
    "build_dry_run_primitives",
    "build_motion_gen_pose_planner",
    "cleaning_zone_to_dict",
    "dry_run_validation_report_to_dict",
    "draw_fixture_overlay",
    "estimate_urinal_frame_from_mask",
    "estimate_urinal_frame_from_roi",
    "fixture_prompt_texts_from_cfg",
    "fixture_registration_mode_from_cfg",
    "fixture_roi_from_cfg",
    "load_fixture_estimate",
    "normalize_fixture_roi",
    "primitive_plan_to_dict",
    "primitive_validation_result_to_dict",
    "resolve_validation_start_q",
    "save_cleaning_zones",
    "save_dry_run_validation_report",
    "save_fixture_estimate",
    "save_primitive_plan",
    "select_best_fixture_mask_candidate",
    "validate_dry_run_primitives",
]
